//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\SlidingTabIndicatorImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SlidingTabIndicatorImpl")
#ifdef RESTRICT_SlidingTabIndicatorImpl
#define INCLUDE_ALL_SlidingTabIndicatorImpl 0
#else
#define INCLUDE_ALL_SlidingTabIndicatorImpl 1
#endif
#undef RESTRICT_SlidingTabIndicatorImpl

#if !defined (ASSlidingTabIndicatorImpl_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl))
#define ASSlidingTabIndicatorImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASSlidingTabIndicatorImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_STATIC_INIT(ASSlidingTabIndicatorImpl)

inline NSString *ASSlidingTabIndicatorImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSlidingTabIndicatorImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSlidingTabIndicatorImpl, LOCAL_NAME, NSString *)

inline NSString *ASSlidingTabIndicatorImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSlidingTabIndicatorImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSlidingTabIndicatorImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_init(ASSlidingTabIndicatorImpl *self);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *new_ASSlidingTabIndicatorImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *create_ASSlidingTabIndicatorImpl_init(void);

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_initWithNSString_(ASSlidingTabIndicatorImpl *self, NSString *localname);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *new_ASSlidingTabIndicatorImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *create_ASSlidingTabIndicatorImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_initWithNSString_withNSString_(ASSlidingTabIndicatorImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *new_ASSlidingTabIndicatorImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *create_ASSlidingTabIndicatorImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl)

@compatibility_alias ComAsheraTablayoutSlidingTabIndicatorImpl ASSlidingTabIndicatorImpl;


#endif

#if !defined (ASSlidingTabIndicatorImpl_Divider_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_Divider))
#define ASSlidingTabIndicatorImpl_Divider_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASSlidingTabIndicatorImpl_Divider : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_Divider)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_Divider_init(ASSlidingTabIndicatorImpl_Divider *self);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_Divider *new_ASSlidingTabIndicatorImpl_Divider_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_Divider *create_ASSlidingTabIndicatorImpl_Divider_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_Divider)


#endif

#if !defined (ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt))
#define ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_

#define RESTRICT_TabLayout 1
#define INCLUDE_ADMTabLayout_SlidingTabIndicator 1
#include "TabLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADMTabLayout;
@class ADRect;
@class ADView;
@class ASSlidingTabIndicatorImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt : ADMTabLayout_SlidingTabIndicator < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASSlidingTabIndicatorImpl:(ASSlidingTabIndicatorImpl *)outer$
                                 withADMTabLayout:(ADMTabLayout *)tablayout;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)removeViewAtWithInt:(int32_t)index;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithADMTabLayout:(ADMTabLayout *)outer$
                       withADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_initWithASSlidingTabIndicatorImpl_withADMTabLayout_(ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt *self, ASSlidingTabIndicatorImpl *outer$, ADMTabLayout *tablayout);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt *new_ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_initWithASSlidingTabIndicatorImpl_withADMTabLayout_(ASSlidingTabIndicatorImpl *outer$, ADMTabLayout *tablayout) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt *create_ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_initWithASSlidingTabIndicatorImpl_withADMTabLayout_(ASSlidingTabIndicatorImpl *outer$, ADMTabLayout *tablayout);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt)


#endif

#pragma pop_macro("INCLUDE_ALL_SlidingTabIndicatorImpl")
