//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\SlidingTabIndicatorImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SlidingTabIndicatorImpl")
#ifdef RESTRICT_SlidingTabIndicatorImpl
#define INCLUDE_ALL_SlidingTabIndicatorImpl 0
#else
#define INCLUDE_ALL_SlidingTabIndicatorImpl 1
#endif
#undef RESTRICT_SlidingTabIndicatorImpl

#if !defined (ASSlidingTabIndicatorImpl_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl))
#define ASSlidingTabIndicatorImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean;
@class ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder;
@class ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder;
@class ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASSlidingTabIndicatorImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean *)getBean;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean *)getParamsBean;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_STATIC_INIT(ASSlidingTabIndicatorImpl)

inline NSString *ASSlidingTabIndicatorImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSlidingTabIndicatorImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSlidingTabIndicatorImpl, LOCAL_NAME, NSString *)

inline NSString *ASSlidingTabIndicatorImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSlidingTabIndicatorImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSlidingTabIndicatorImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_init(ASSlidingTabIndicatorImpl *self);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *new_ASSlidingTabIndicatorImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *create_ASSlidingTabIndicatorImpl_init(void);

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_initWithNSString_(ASSlidingTabIndicatorImpl *self, NSString *localname);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *new_ASSlidingTabIndicatorImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *create_ASSlidingTabIndicatorImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_initWithNSString_withNSString_(ASSlidingTabIndicatorImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *new_ASSlidingTabIndicatorImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl *create_ASSlidingTabIndicatorImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl)

@compatibility_alias ComAsheraTablayoutSlidingTabIndicatorImpl ASSlidingTabIndicatorImpl;

#endif

#if !defined (ASSlidingTabIndicatorImpl_Divider_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_Divider))
#define ASSlidingTabIndicatorImpl_Divider_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASSlidingTabIndicatorImpl_Divider : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_Divider)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_Divider_init(ASSlidingTabIndicatorImpl_Divider *self);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_Divider *new_ASSlidingTabIndicatorImpl_Divider_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_Divider *create_ASSlidingTabIndicatorImpl_Divider_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_Divider)

#endif

#if !defined (ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt))
#define ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_

#define RESTRICT_TabLayout 1
#define INCLUDE_ADMTabLayout_SlidingTabIndicator 1
#include "TabLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADMTabLayout;
@class ADRect;
@class ADView;
@class ASSlidingTabIndicatorImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt : ADMTabLayout_SlidingTabIndicator < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASSlidingTabIndicatorImpl:(ASSlidingTabIndicatorImpl *)outer$
                                 withADMTabLayout:(ADMTabLayout *)tablayout;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)removeViewAtWithInt:(jint)index;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithADMTabLayout:(ADMTabLayout *)outer$
                       withADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_initWithASSlidingTabIndicatorImpl_withADMTabLayout_(ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt *self, ASSlidingTabIndicatorImpl *outer$, ADMTabLayout *tablayout);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt *new_ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_initWithASSlidingTabIndicatorImpl_withADMTabLayout_(ASSlidingTabIndicatorImpl *outer$, ADMTabLayout *tablayout) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt *create_ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt_initWithASSlidingTabIndicatorImpl_withADMTabLayout_(ASSlidingTabIndicatorImpl *outer$, ADMTabLayout *tablayout);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_SlidingTabIndicatorExt)

#endif

#if !defined (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder))
#define ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASSlidingTabIndicatorImpl;

@interface ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASSlidingTabIndicatorImpl:(ASSlidingTabIndicatorImpl *)outer$;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                                withId:(id)arg1;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)addModelWithId:(id)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)endAnimator;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getBaselineAlignedChildIndex;

- (id)getDivider;

- (id)getDividerPadding;

- (id)getGravity;

- (id)getShowDividers;

- (id)getWeightSum;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)invalidate;

- (id)isBaselineAligned;

- (id)isMeasureWithLargestChild;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)requestLayout;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)reset;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setBaselineAlignedWithBoolean:(jboolean)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setBaselineAlignedChildIndexWithInt:(jint)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setDividerWithNSString:(NSString *)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setDividerPaddingWithNSString:(NSString *)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setGravityWithNSString:(NSString *)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setMeasureWithLargestChildWithBoolean:(jboolean)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setShowDividersWithNSString:(NSString *)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setWeightSumWithFloat:(jfloat)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)startAnimator;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetAddStatesFromChildren;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetAlpha;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetBackground;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetBackgroundTint;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetBackgroundTintMode;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetBaselineAligned;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetBaselineAlignedChildIndex;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetBottom;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetClickable;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetClipChildren;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetClipToPadding;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetContentDescription;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetDivider;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetDividerPadding;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetDuplicateParentState;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetEnabled;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetFocusable;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetForeground;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetForegroundGravity;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetForegroundTint;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetForegroundTintMode;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetGravity;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetId;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosAccessibilityHint;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosAccessibilityValue;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosAlpha;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosBackgroundColor;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosClipsToBounds;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosContentScaleFactor;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosIsFocused;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosIsHidden;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosIsOpaque;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosLargeContentImage;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosLargeContentTitle;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosTag;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosTintColor;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetKeepScreenOn;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetLayoutDirection;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetLayoutMode;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetLeft;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetLongClickable;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetMaxHeight;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetMaxWidth;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetMeasureWithLargestChild;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetMinHeight;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetMinWidth;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetModelDescPath;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetModelIdPath;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetModelParam;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetModelPojoToUi;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetModelSyncEvents;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetModelUiToPojo;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetPaddingBottom;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetPaddingEnd;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetPaddingLeft;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetPaddingRight;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetPaddingStart;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetPaddingTop;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetRight;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetRotation;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetRotationX;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetRotationY;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetScaleX;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetScaleY;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetSelected;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetShowDividers;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTextAlignment;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTextDirection;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTop;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTransformPivotX;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTransformPivotY;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTranslationX;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTranslationY;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetTranslationZ;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetValidateForm;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetVisibility;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)tryGetWeightSum;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                      withId:(id)arg1;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *self, ASSlidingTabIndicatorImpl *outer$);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *new_ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder *create_ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandBuilder)

#endif

#if !defined (ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean))
#define ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASSlidingTabIndicatorImpl;
@protocol ASIWidget;

@interface ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASSlidingTabIndicatorImpl:(ASSlidingTabIndicatorImpl *)outer$;

- (id)getBaselineAlignedChildIndex;

- (id)getDivider;

- (id)getDividerPadding;

- (id)getGravity;

- (id)getShowDividers;

- (id)getWeightSum;

- (id)isBaselineAligned;

- (id)isMeasureWithLargestChild;

- (void)setBaselineAlignedWithBoolean:(jboolean)value;

- (void)setBaselineAlignedChildIndexWithInt:(jint)value;

- (void)setDividerWithNSString:(NSString *)value;

- (void)setDividerPaddingWithNSString:(NSString *)value;

- (void)setGravityWithNSString:(NSString *)value;

- (void)setMeasureWithLargestChildWithBoolean:(jboolean)value;

- (void)setShowDividersWithNSString:(NSString *)value;

- (void)setWeightSumWithFloat:(jfloat)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean *self, ASSlidingTabIndicatorImpl *outer$);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean *new_ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean *create_ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_SlidingTabIndicatorBean)

#endif

#if !defined (ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean))
#define ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASSlidingTabIndicatorImpl;
@protocol ASIWidget;

@interface ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASSlidingTabIndicatorImpl:(ASSlidingTabIndicatorImpl *)outer$;

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutWeightWithASIWidget:(id<ASIWidget>)w;

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value;

- (void)setLayoutWeightWithASIWidget:(id<ASIWidget>)w
                           withFloat:(jfloat)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean *self, ASSlidingTabIndicatorImpl *outer$);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean *new_ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean *create_ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_SlidingTabIndicatorParamsBean)

#endif

#if !defined (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder_) && (INCLUDE_ALL_SlidingTabIndicatorImpl || defined(INCLUDE_ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder))
#define ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASSlidingTabIndicatorImpl;

@interface ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASSlidingTabIndicatorImpl:(ASSlidingTabIndicatorImpl *)outer$;

- (id)getLayoutGravity;

- (id)getLayoutWeight;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)reset;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)setLayoutWeightWithFloat:(jfloat)value;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutGravity;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutMarginTop;

- (ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *)tryGetLayoutWeight;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder)

FOUNDATION_EXPORT void ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *self, ASSlidingTabIndicatorImpl *outer$);

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *new_ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder *create_ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder_initWithASSlidingTabIndicatorImpl_(ASSlidingTabIndicatorImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSlidingTabIndicatorImpl_SlidingTabIndicatorCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_SlidingTabIndicatorImpl")
