//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\TabItemImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TabItemImpl")
#ifdef RESTRICT_TabItemImpl
#define INCLUDE_ALL_TabItemImpl 0
#else
#define INCLUDE_ALL_TabItemImpl 1
#endif
#undef RESTRICT_TabItemImpl

#if !defined (ASTabItemImpl_) && (INCLUDE_ALL_TabItemImpl || defined(INCLUDE_ASTabItemImpl))
#define ASTabItemImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASTabItemImpl : ASBaseWidget {
 @public
  id uiView_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (id)asNativeWidget;

- (id)asWidget;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)createView;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getCustomTabiconId;

- (id)getCustomTabTitleId;

- (id)getIcon;

- (id)getLayout;

- (id)getTabItemid;

- (id)getText;

- (IOSClass *)getViewClass;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setCustomTabiconIdWithId:(id)customTabiconId;

- (void)setCustomTabTitleIdWithId:(id)customTabTitleId;

- (void)setIconWithId:(id)icon;

- (void)setLayoutWithId:(id)layout;

- (void)setTabItemidWithId:(id)tabItemid;

- (void)setTextWithId:(id)text;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
                    withNSString:(NSString *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabItemImpl)

J2OBJC_FIELD_SETTER(ASTabItemImpl, uiView_, id)

inline NSString *ASTabItemImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabItemImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabItemImpl, LOCAL_NAME, NSString *)

inline NSString *ASTabItemImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabItemImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabItemImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASTabItemImpl_init(ASTabItemImpl *self);

FOUNDATION_EXPORT ASTabItemImpl *new_ASTabItemImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabItemImpl *create_ASTabItemImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabItemImpl)

@compatibility_alias ComAsheraTablayoutTabItemImpl ASTabItemImpl;

#endif

#if !defined (ASTabItemImpl_ViewExt_) && (INCLUDE_ALL_TabItemImpl || defined(INCLUDE_ASTabItemImpl_ViewExt))
#define ASTabItemImpl_ViewExt_

#define RESTRICT_View 1
#define INCLUDE_ADView 1
#include "View.h"

#define RESTRICT_IViewStub 1
#define INCLUDE_ASIViewStub 1
#include "IViewStub.h"

@class ASTabItemImpl;

@interface ASTabItemImpl_ViewExt : ADView < ASIViewStub >

#pragma mark Public

- (instancetype)initWithASTabItemImpl:(ASTabItemImpl *)outer$;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)remeasure;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabItemImpl_ViewExt)

FOUNDATION_EXPORT void ASTabItemImpl_ViewExt_initWithASTabItemImpl_(ASTabItemImpl_ViewExt *self, ASTabItemImpl *outer$);

FOUNDATION_EXPORT ASTabItemImpl_ViewExt *new_ASTabItemImpl_ViewExt_initWithASTabItemImpl_(ASTabItemImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabItemImpl_ViewExt *create_ASTabItemImpl_ViewExt_initWithASTabItemImpl_(ASTabItemImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTabItemImpl_ViewExt)

#endif

#pragma pop_macro("INCLUDE_ALL_TabItemImpl")
