//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\TabLayoutPlugin.java
//

#include "J2ObjC_source.h"
#include "SlidingTabIndicatorImpl.h"
#include "TabItemImpl.h"
#include "TabLayoutImpl.h"
#include "TabLayoutPlugin.h"
#include "TabViewImpl.h"
#include "WidgetFactory.h"


@implementation ASTabLayoutPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASTabLayoutPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASTabLayoutPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASTabLayoutPlugin = { "TabLayoutPlugin", "com.ashera.tablayout", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASTabLayoutPlugin;
}

@end

void ASTabLayoutPlugin_init(ASTabLayoutPlugin *self) {
  NSObject_init(self);
}

ASTabLayoutPlugin *new_ASTabLayoutPlugin_init() {
  J2OBJC_NEW_IMPL(ASTabLayoutPlugin, init)
}

ASTabLayoutPlugin *create_ASTabLayoutPlugin_init() {
  J2OBJC_CREATE_IMPL(ASTabLayoutPlugin, init)
}

void ASTabLayoutPlugin_initPlugin() {
  ASTabLayoutPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASSlidingTabIndicatorImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASTabViewImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASTabLayoutImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASTabItemImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabLayoutPlugin)
