//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\TabLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TabLayoutImpl")
#ifdef RESTRICT_TabLayoutImpl
#define INCLUDE_ALL_TabLayoutImpl 0
#else
#define INCLUDE_ALL_TabLayoutImpl 1
#endif
#undef RESTRICT_TabLayoutImpl

#if !defined (ASTabLayoutImpl_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl))
#define ASTabLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ADMTabLayout_Tab;
@class ASTabLayoutImpl_TabLayoutBean;
@class ASTabLayoutImpl_TabLayoutCommandBuilder;
@class ASTabLayoutImpl_TabLayoutCommandParamsBuilder;
@class ASTabLayoutImpl_TabLayoutParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
               withADMTabLayout_Tab:(ADMTabLayout_Tab *)tab
                    withASIFragment:(id<ASIFragment>)fragment;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASTabLayoutImpl_TabLayoutBean *)getBean;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASTabLayoutImpl_TabLayoutParamsBean *)getParamsBean;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (id)getScrollX;

- (id)getScrollY;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (jdouble)nativeGetScrollXWithId:(id)view;

- (jdouble)nativeGetScrollYWithId:(id)view;

- (id)nativeHscrollViewCreate;

- (void)nativeSetScrollXWithId:(id)view
                       withInt:(jint)value;

- (void)nativeSetScrollYWithId:(id)view
                       withInt:(jint)value;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl)

inline NSString *ASTabLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASTabLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASTabLayoutImpl_init(ASTabLayoutImpl *self);

FOUNDATION_EXPORT ASTabLayoutImpl *new_ASTabLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl *create_ASTabLayoutImpl_init(void);

FOUNDATION_EXPORT void ASTabLayoutImpl_initWithNSString_(ASTabLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASTabLayoutImpl *new_ASTabLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl *create_ASTabLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASTabLayoutImpl_initWithNSString_withNSString_(ASTabLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASTabLayoutImpl *new_ASTabLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl *create_ASTabLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

FOUNDATION_EXPORT void ASTabLayoutImpl_addEventInfoWithJavaUtilMap_withADMTabLayout_Tab_withASIFragment_(id<JavaUtilMap> obj, ADMTabLayout_Tab *tab, id<ASIFragment> fragment);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl)

@compatibility_alias ComAsheraTablayoutTabLayoutImpl ASTabLayoutImpl;

#endif

#if !defined (ASTabLayoutImpl_TabGravity_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabGravity))
#define ASTabLayoutImpl_TabGravity_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabGravity : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabGravity)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabGravity_init(ASTabLayoutImpl_TabGravity *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabGravity *new_ASTabLayoutImpl_TabGravity_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabGravity *create_ASTabLayoutImpl_TabGravity_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabGravity)

#endif

#if !defined (ASTabLayoutImpl_TabIndicatorAnimationMode_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabIndicatorAnimationMode))
#define ASTabLayoutImpl_TabIndicatorAnimationMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabIndicatorAnimationMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabIndicatorAnimationMode)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabIndicatorAnimationMode_init(ASTabLayoutImpl_TabIndicatorAnimationMode *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorAnimationMode *new_ASTabLayoutImpl_TabIndicatorAnimationMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorAnimationMode *create_ASTabLayoutImpl_TabIndicatorAnimationMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabIndicatorAnimationMode)

#endif

#if !defined (ASTabLayoutImpl_TabIndicatorGravity_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabIndicatorGravity))
#define ASTabLayoutImpl_TabIndicatorGravity_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabIndicatorGravity : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabIndicatorGravity)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabIndicatorGravity_init(ASTabLayoutImpl_TabIndicatorGravity *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorGravity *new_ASTabLayoutImpl_TabIndicatorGravity_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorGravity *create_ASTabLayoutImpl_TabIndicatorGravity_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabIndicatorGravity)

#endif

#if !defined (ASTabLayoutImpl_TabMode_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabMode))
#define ASTabLayoutImpl_TabMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabMode)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabMode_init(ASTabLayoutImpl_TabMode *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabMode *new_ASTabLayoutImpl_TabMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabMode *create_ASTabLayoutImpl_TabMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabMode)

#endif

#if !defined (ASTabLayoutImpl_TabLayoutExt_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabLayoutExt))
#define ASTabLayoutImpl_TabLayoutExt_

#define RESTRICT_TabLayout 1
#define INCLUDE_ADMTabLayout 1
#include "TabLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASTabLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASTabLayoutImpl_TabLayoutExt : ADMTabLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASTabLayoutImpl:(ASTabLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabLayoutExt)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabLayoutExt_initWithASTabLayoutImpl_(ASTabLayoutImpl_TabLayoutExt *self, ASTabLayoutImpl *outer$);

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutExt *new_ASTabLayoutImpl_TabLayoutExt_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutExt *create_ASTabLayoutImpl_TabLayoutExt_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabLayoutExt)

#endif

#if !defined (ASTabLayoutImpl_ValueSetter_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_ValueSetter))
#define ASTabLayoutImpl_ValueSetter_

@class ADXBadgeDrawable;

@protocol ASTabLayoutImpl_ValueSetter < JavaObject >

- (void)setValueOnBadgeDrawableWithADXBadgeDrawable:(ADXBadgeDrawable *)badgeDrawable
                                             withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_ValueSetter)

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_ValueSetter)

#endif

#if !defined (ASTabLayoutImpl_TabLayoutCommandBuilder_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabLayoutCommandBuilder))
#define ASTabLayoutImpl_TabLayoutCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASTabLayoutImpl;

@interface ASTabLayoutImpl_TabLayoutCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASTabLayoutImpl:(ASTabLayoutImpl *)outer$;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                            withId:(id)arg1;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)addModelWithId:(id)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)addTabWithNSString:(NSString *)text
                                                   withNSString:(NSString *)icon
                                                   withNSString:(NSString *)id_
                                                   withNSString:(NSString *)layout
                                                   withNSString:(NSString *)customTabTitleId
                                                   withNSString:(NSString *)customTabiconId
                                                   withNSString:(NSString *)where;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)endAnimator;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getScrollX;

- (id)getTabIndicatorAnimationMode;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)invalidate;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)removeAllTabs;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)removeTabWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)removeTabAtWithInt:(jint)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)requestLayout;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)reset;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)selectTabWithInt:(jint)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeAlphasWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeBackgroundColorsWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeGravitiesWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeHorizontalOffsetsWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeIsVisiblesWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeMaxCharacterCountsWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeNumbersWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeTextAppearanceResourcesWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeTextColorsWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBadgeVerticalOffsetsWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setMenuItemIdsWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnTabReselectedWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnTabSelectedWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnTabUnselectedWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setScrollXWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabBackgroundWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabContentStartWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabGravityWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabIconTintWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabIndicatorAnimationModeWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabIndicatorColorWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabIndicatorFullWidthWithBoolean:(jboolean)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabIndicatorGravityWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabIndicatorHeightWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabInlineLabelWithBoolean:(jboolean)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabMaxWidthWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabMinWidthWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabModeWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabPaddingWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabPaddingBottomWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabPaddingEndWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabPaddingStartWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabPaddingTopWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabSelectedTextColorWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabTextAppearanceWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTabTextColorWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setupWithViewPagerWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)startAnimator;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetAddStatesFromChildren;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetAlpha;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetBackground;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetBackgroundTint;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetBackgroundTintMode;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetBottom;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetClickable;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetClipChildren;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetClipToPadding;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetContentDescription;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetDuplicateParentState;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetEnabled;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetFocusable;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetForeground;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetForegroundGravity;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetForegroundTint;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetForegroundTintMode;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetId;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosAccessibilityHint;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosAccessibilityValue;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosAlpha;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosBackgroundColor;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosClipsToBounds;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosContentScaleFactor;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosIsFocused;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosIsHidden;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosIsOpaque;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosLargeContentImage;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosLargeContentTitle;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosTag;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosTintColor;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetKeepScreenOn;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetLayoutDirection;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetLayoutMode;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetLeft;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetLongClickable;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetMaxHeight;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetMaxWidth;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetMinHeight;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetMinWidth;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetModelDescPath;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetModelIdPath;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetModelParam;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetModelPojoToUi;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetModelSyncEvents;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetModelUiToPojo;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetPaddingBottom;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetPaddingEnd;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetPaddingLeft;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetPaddingRight;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetPaddingStart;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetPaddingTop;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetRight;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetRotation;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetRotationX;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetRotationY;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetScaleX;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetScaleY;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetScrollX;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetSelected;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTabIndicatorAnimationMode;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTextAlignment;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTextDirection;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTop;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTransformPivotX;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTransformPivotY;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTranslationX;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTranslationY;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetTranslationZ;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetValidateForm;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)tryGetVisibility;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                  withId:(id)arg1;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)updateTabTextsWithNSString:(NSString *)value;

- (ASTabLayoutImpl_TabLayoutCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabLayoutCommandBuilder)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabLayoutCommandBuilder_initWithASTabLayoutImpl_(ASTabLayoutImpl_TabLayoutCommandBuilder *self, ASTabLayoutImpl *outer$);

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutCommandBuilder *new_ASTabLayoutImpl_TabLayoutCommandBuilder_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutCommandBuilder *create_ASTabLayoutImpl_TabLayoutCommandBuilder_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabLayoutCommandBuilder)

#endif

#if !defined (ASTabLayoutImpl_TabLayoutBean_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabLayoutBean))
#define ASTabLayoutImpl_TabLayoutBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASTabLayoutImpl;
@protocol ASIWidget;

@interface ASTabLayoutImpl_TabLayoutBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASTabLayoutImpl:(ASTabLayoutImpl *)outer$;

- (void)addTabWithNSString:(NSString *)text
              withNSString:(NSString *)icon
              withNSString:(NSString *)id_
              withNSString:(NSString *)layout
              withNSString:(NSString *)customTabTitleId
              withNSString:(NSString *)customTabiconId
              withNSString:(NSString *)where;

- (id)getScrollX;

- (id)getTabIndicatorAnimationMode;

- (void)removeAllTabs;

- (void)removeTabWithNSString:(NSString *)value;

- (void)removeTabAtWithInt:(jint)value;

- (void)selectTabWithInt:(jint)value;

- (void)setBadgeAlphasWithNSString:(NSString *)value;

- (void)setBadgeBackgroundColorsWithNSString:(NSString *)value;

- (void)setBadgeGravitiesWithNSString:(NSString *)value;

- (void)setBadgeHorizontalOffsetsWithNSString:(NSString *)value;

- (void)setBadgeIsVisiblesWithNSString:(NSString *)value;

- (void)setBadgeMaxCharacterCountsWithNSString:(NSString *)value;

- (void)setBadgeNumbersWithNSString:(NSString *)value;

- (void)setBadgeTextAppearanceResourcesWithNSString:(NSString *)value;

- (void)setBadgeTextColorsWithNSString:(NSString *)value;

- (void)setBadgeVerticalOffsetsWithNSString:(NSString *)value;

- (void)setMenuItemIdsWithNSString:(NSString *)value;

- (void)setOnTabReselectedWithNSString:(NSString *)value;

- (void)setOnTabSelectedWithNSString:(NSString *)value;

- (void)setOnTabUnselectedWithNSString:(NSString *)value;

- (void)setScrollXWithNSString:(NSString *)value;

- (void)setTabBackgroundWithNSString:(NSString *)value;

- (void)setTabContentStartWithNSString:(NSString *)value;

- (void)setTabGravityWithNSString:(NSString *)value;

- (void)setTabIconTintWithNSString:(NSString *)value;

- (void)setTabIndicatorAnimationModeWithNSString:(NSString *)value;

- (void)setTabIndicatorColorWithNSString:(NSString *)value;

- (void)setTabIndicatorFullWidthWithBoolean:(jboolean)value;

- (void)setTabIndicatorGravityWithNSString:(NSString *)value;

- (void)setTabIndicatorHeightWithNSString:(NSString *)value;

- (void)setTabInlineLabelWithBoolean:(jboolean)value;

- (void)setTabMaxWidthWithNSString:(NSString *)value;

- (void)setTabMinWidthWithNSString:(NSString *)value;

- (void)setTabModeWithNSString:(NSString *)value;

- (void)setTabPaddingWithNSString:(NSString *)value;

- (void)setTabPaddingBottomWithNSString:(NSString *)value;

- (void)setTabPaddingEndWithNSString:(NSString *)value;

- (void)setTabPaddingStartWithNSString:(NSString *)value;

- (void)setTabPaddingTopWithNSString:(NSString *)value;

- (void)setTabSelectedTextColorWithNSString:(NSString *)value;

- (void)setTabTextAppearanceWithNSString:(NSString *)value;

- (void)setTabTextColorWithNSString:(NSString *)value;

- (void)setupWithViewPagerWithNSString:(NSString *)value;

- (void)updateTabTextsWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabLayoutBean)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabLayoutBean_initWithASTabLayoutImpl_(ASTabLayoutImpl_TabLayoutBean *self, ASTabLayoutImpl *outer$);

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutBean *new_ASTabLayoutImpl_TabLayoutBean_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutBean *create_ASTabLayoutImpl_TabLayoutBean_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabLayoutBean)

#endif

#if !defined (ASTabLayoutImpl_TabLayoutParamsBean_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabLayoutParamsBean))
#define ASTabLayoutImpl_TabLayoutParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASTabLayoutImpl;

@interface ASTabLayoutImpl_TabLayoutParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASTabLayoutImpl:(ASTabLayoutImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabLayoutParamsBean)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabLayoutParamsBean_initWithASTabLayoutImpl_(ASTabLayoutImpl_TabLayoutParamsBean *self, ASTabLayoutImpl *outer$);

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutParamsBean *new_ASTabLayoutImpl_TabLayoutParamsBean_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutParamsBean *create_ASTabLayoutImpl_TabLayoutParamsBean_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabLayoutParamsBean)

#endif

#if !defined (ASTabLayoutImpl_TabLayoutCommandParamsBuilder_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabLayoutCommandParamsBuilder))
#define ASTabLayoutImpl_TabLayoutCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASTabLayoutImpl;

@interface ASTabLayoutImpl_TabLayoutCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASTabLayoutImpl:(ASTabLayoutImpl *)outer$;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)reset;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASTabLayoutImpl_TabLayoutCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabLayoutCommandParamsBuilder)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabLayoutCommandParamsBuilder_initWithASTabLayoutImpl_(ASTabLayoutImpl_TabLayoutCommandParamsBuilder *self, ASTabLayoutImpl *outer$);

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutCommandParamsBuilder *new_ASTabLayoutImpl_TabLayoutCommandParamsBuilder_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutCommandParamsBuilder *create_ASTabLayoutImpl_TabLayoutCommandParamsBuilder_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabLayoutCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_TabLayoutImpl")
