//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\TabLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TabLayoutImpl")
#ifdef RESTRICT_TabLayoutImpl
#define INCLUDE_ALL_TabLayoutImpl 0
#else
#define INCLUDE_ALL_TabLayoutImpl 1
#endif
#undef RESTRICT_TabLayoutImpl

#if !defined (ASTabLayoutImpl_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl))
#define ASTabLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ADMTabLayout_Tab;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

+ (void)addEventInfoWithJavaUtilMap:(id<JavaUtilMap>)obj
               withADMTabLayout_Tab:(ADMTabLayout_Tab *)tab
                    withASIFragment:(id<ASIFragment>)fragment;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (id)getScrollX;

- (id)getScrollY;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (jdouble)nativeGetScrollXWithId:(id)view;

- (jdouble)nativeGetScrollYWithId:(id)view;

- (id)nativeHscrollViewCreate;

- (void)nativeSetScrollXWithId:(id)view
                       withInt:(jint)value;

- (void)nativeSetScrollYWithId:(id)view
                       withInt:(jint)value;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl)

inline NSString *ASTabLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASTabLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASTabLayoutImpl_init(ASTabLayoutImpl *self);

FOUNDATION_EXPORT ASTabLayoutImpl *new_ASTabLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl *create_ASTabLayoutImpl_init(void);

FOUNDATION_EXPORT void ASTabLayoutImpl_initWithNSString_(ASTabLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASTabLayoutImpl *new_ASTabLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl *create_ASTabLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASTabLayoutImpl_initWithNSString_withNSString_(ASTabLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASTabLayoutImpl *new_ASTabLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl *create_ASTabLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

FOUNDATION_EXPORT void ASTabLayoutImpl_addEventInfoWithJavaUtilMap_withADMTabLayout_Tab_withASIFragment_(id<JavaUtilMap> obj, ADMTabLayout_Tab *tab, id<ASIFragment> fragment);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl)

@compatibility_alias ComAsheraTablayoutTabLayoutImpl ASTabLayoutImpl;

#endif

#if !defined (ASTabLayoutImpl_TabGravity_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabGravity))
#define ASTabLayoutImpl_TabGravity_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabGravity : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabGravity)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabGravity_init(ASTabLayoutImpl_TabGravity *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabGravity *new_ASTabLayoutImpl_TabGravity_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabGravity *create_ASTabLayoutImpl_TabGravity_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabGravity)

#endif

#if !defined (ASTabLayoutImpl_TabIndicatorAnimationMode_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabIndicatorAnimationMode))
#define ASTabLayoutImpl_TabIndicatorAnimationMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabIndicatorAnimationMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabIndicatorAnimationMode)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabIndicatorAnimationMode_init(ASTabLayoutImpl_TabIndicatorAnimationMode *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorAnimationMode *new_ASTabLayoutImpl_TabIndicatorAnimationMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorAnimationMode *create_ASTabLayoutImpl_TabIndicatorAnimationMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabIndicatorAnimationMode)

#endif

#if !defined (ASTabLayoutImpl_TabIndicatorGravity_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabIndicatorGravity))
#define ASTabLayoutImpl_TabIndicatorGravity_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabIndicatorGravity : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabIndicatorGravity)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabIndicatorGravity_init(ASTabLayoutImpl_TabIndicatorGravity *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorGravity *new_ASTabLayoutImpl_TabIndicatorGravity_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabIndicatorGravity *create_ASTabLayoutImpl_TabIndicatorGravity_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabIndicatorGravity)

#endif

#if !defined (ASTabLayoutImpl_TabMode_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabMode))
#define ASTabLayoutImpl_TabMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabLayoutImpl_TabMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabMode)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabMode_init(ASTabLayoutImpl_TabMode *self);

FOUNDATION_EXPORT ASTabLayoutImpl_TabMode *new_ASTabLayoutImpl_TabMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabMode *create_ASTabLayoutImpl_TabMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabMode)

#endif

#if !defined (ASTabLayoutImpl_TabLayoutExt_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_TabLayoutExt))
#define ASTabLayoutImpl_TabLayoutExt_

#define RESTRICT_TabLayout 1
#define INCLUDE_ADMTabLayout 1
#include "TabLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASTabLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASTabLayoutImpl_TabLayoutExt : ADMTabLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASTabLayoutImpl:(ASTabLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_TabLayoutExt)

FOUNDATION_EXPORT void ASTabLayoutImpl_TabLayoutExt_initWithASTabLayoutImpl_(ASTabLayoutImpl_TabLayoutExt *self, ASTabLayoutImpl *outer$);

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutExt *new_ASTabLayoutImpl_TabLayoutExt_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutImpl_TabLayoutExt *create_ASTabLayoutImpl_TabLayoutExt_initWithASTabLayoutImpl_(ASTabLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_TabLayoutExt)

#endif

#if !defined (ASTabLayoutImpl_ValueSetter_) && (INCLUDE_ALL_TabLayoutImpl || defined(INCLUDE_ASTabLayoutImpl_ValueSetter))
#define ASTabLayoutImpl_ValueSetter_

@class ADXBadgeDrawable;

@protocol ASTabLayoutImpl_ValueSetter < JavaObject >

- (void)setValueOnBadgeDrawableWithADXBadgeDrawable:(ADXBadgeDrawable *)badgeDrawable
                                             withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutImpl_ValueSetter)

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutImpl_ValueSetter)

#endif

#pragma pop_macro("INCLUDE_ALL_TabLayoutImpl")
