//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\TabLayoutPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TabLayoutPlugin")
#ifdef RESTRICT_TabLayoutPlugin
#define INCLUDE_ALL_TabLayoutPlugin 0
#else
#define INCLUDE_ALL_TabLayoutPlugin 1
#endif
#undef RESTRICT_TabLayoutPlugin

#if !defined (ASTabLayoutPlugin_) && (INCLUDE_ALL_TabLayoutPlugin || defined(INCLUDE_ASTabLayoutPlugin))
#define ASTabLayoutPlugin_

@interface ASTabLayoutPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabLayoutPlugin)

FOUNDATION_EXPORT void ASTabLayoutPlugin_init(ASTabLayoutPlugin *self);

FOUNDATION_EXPORT ASTabLayoutPlugin *new_ASTabLayoutPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabLayoutPlugin *create_ASTabLayoutPlugin_init(void);

FOUNDATION_EXPORT void ASTabLayoutPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabLayoutPlugin)

@compatibility_alias ComAsheraTablayoutTabLayoutPlugin ASTabLayoutPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_TabLayoutPlugin")
