//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\TabViewImpl.java
//

#include "AbstractBitFlagConverter.h"
#include "BaseHasWidgets.h"
#include "Canvas.h"
#include "Context.h"
#include "ConverterFactory.h"
#include "Drawable.h"
#include "HasWidgets.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "LayoutTransition.h"
#include "LinearLayout.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "Rect.h"
#include "TabLayout.h"
#include "TabViewImpl.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"

#include "ASUIImageView.h"

@protocol JavaUtilList;
@protocol JavaUtilMap;


#pragma clang diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ASTabViewImpl () {
 @public
  id uiView_;
  id<ADCanvas> canvas_;
  ADMTabLayout_TabView *tabView_;
  ASTabViewImpl_TabViewCommandBuilder *builder_;
  ASTabViewImpl_TabViewBean *bean_;
  ASTabViewImpl_TabViewCommandParamsBuilder *paramsBuilder_;
  ASTabViewImpl_TabViewParamsBean *paramsBean_;
}

- (void)setWidgetOnNativeClass;

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ADLinearLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

- (void)setDividerPaddingWithId:(id)objValue;

- (void)setShowDividersWithId:(id)objValue;

- (id)getDividerPadding;

- (id)getShowDividers;

- (void)createCanvas;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

@end

J2OBJC_FIELD_SETTER(ASTabViewImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASTabViewImpl, canvas_, id<ADCanvas>)
J2OBJC_FIELD_SETTER(ASTabViewImpl, tabView_, ADMTabLayout_TabView *)
J2OBJC_FIELD_SETTER(ASTabViewImpl, builder_, ASTabViewImpl_TabViewCommandBuilder *)
J2OBJC_FIELD_SETTER(ASTabViewImpl, bean_, ASTabViewImpl_TabViewBean *)
J2OBJC_FIELD_SETTER(ASTabViewImpl, paramsBuilder_, ASTabViewImpl_TabViewCommandParamsBuilder *)
J2OBJC_FIELD_SETTER(ASTabViewImpl, paramsBean_, ASTabViewImpl_TabViewParamsBean *)

__attribute__((unused)) static void ASTabViewImpl_setWidgetOnNativeClass(ASTabViewImpl *self);

__attribute__((unused)) static void ASTabViewImpl_nativeRemoveViewWithASIWidget_(ASTabViewImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static void ASTabViewImpl_createLayoutParamsWithADView_(ASTabViewImpl *self, ADView *view);

__attribute__((unused)) static ADLinearLayout_LayoutParams *ASTabViewImpl_getLayoutParamsWithADView_(ASTabViewImpl *self, ADView *view);

__attribute__((unused)) static void ASTabViewImpl_setDividerPaddingWithId_(ASTabViewImpl *self, id objValue);

__attribute__((unused)) static void ASTabViewImpl_setShowDividersWithId_(ASTabViewImpl *self, id objValue);

__attribute__((unused)) static id ASTabViewImpl_getDividerPadding(ASTabViewImpl *self);

__attribute__((unused)) static id ASTabViewImpl_getShowDividers(ASTabViewImpl *self);

__attribute__((unused)) static void ASTabViewImpl_createCanvas(ASTabViewImpl *self);

__attribute__((unused)) static void ASTabViewImpl_nativeCreateWithJavaUtilMap_(ASTabViewImpl *self, id<JavaUtilMap> params);

@interface ASTabViewImpl_Divider () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASTabViewImpl_Divider, mapping_, id<JavaUtilMap>)

@interface ASTabViewImpl_TabViewExt () {
 @public
  __unsafe_unretained ASTabViewImpl *this$1_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  id<JavaUtilList> overlays_;
  jint mMaxWidth_;
  jint mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASTabViewImpl_TabViewExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASTabViewImpl_TabViewExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASTabViewImpl_TabViewExt, overlays_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASTabViewImpl_TabViewExt, templates_, id<JavaUtilMap>)

@interface ASTabViewImpl_CanvasImpl : NSObject < ADCanvas > {
 @public
  jboolean canvasReset_;
  jboolean requiresAttrChangeListener_;
  id<JavaUtilList> imageViews_;
  __unsafe_unretained id<ASIWidget> widget_;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget;

- (void)drawWithADDrawable:(ADDrawable *)mDivider;

- (void)reset;

- (id)nativeCreateImageViewWithId:(id)image;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabViewImpl_CanvasImpl)

J2OBJC_FIELD_SETTER(ASTabViewImpl_CanvasImpl, imageViews_, id<JavaUtilList>)

__attribute__((unused)) static void ASTabViewImpl_CanvasImpl_initWithASIWidget_(ASTabViewImpl_CanvasImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static ASTabViewImpl_CanvasImpl *new_ASTabViewImpl_CanvasImpl_initWithASIWidget_(id<ASIWidget> widget) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASTabViewImpl_CanvasImpl *create_ASTabViewImpl_CanvasImpl_initWithASIWidget_(id<ASIWidget> widget);

J2OBJC_TYPE_LITERAL_HEADER(ASTabViewImpl_CanvasImpl)

@interface ASTabViewImpl_CanvasImpl_$Lambda$1 : NSObject < ADDrawable_AttributeChangeListener > {
 @public
  id val$imageView_;
}

- (void)onAttributeChangeWithNSString:(NSString *)name
                               withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabViewImpl_CanvasImpl_$Lambda$1)

__attribute__((unused)) static void ASTabViewImpl_CanvasImpl_$Lambda$1_initWithId_(ASTabViewImpl_CanvasImpl_$Lambda$1 *self, id capture$0);

__attribute__((unused)) static ASTabViewImpl_CanvasImpl_$Lambda$1 *new_ASTabViewImpl_CanvasImpl_$Lambda$1_initWithId_(id capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASTabViewImpl_CanvasImpl_$Lambda$1 *create_ASTabViewImpl_CanvasImpl_$Lambda$1_initWithId_(id capture$0);

@interface ASTabViewImpl_TabViewCommandBuilder () {
 @public
  ASTabViewImpl *this$0_;
}

@end

@interface ASTabViewImpl_TabViewBean () {
 @public
  ASTabViewImpl *this$0_;
}

@end

@interface ASTabViewImpl_TabViewParamsBean () {
 @public
  ASTabViewImpl *this$0_;
}

@end

@interface ASTabViewImpl_$Lambda$1 : NSObject < JavaLangRunnable > {
 @public
  id<ASIWidget> val$widget_;
}

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabViewImpl_$Lambda$1)

__attribute__((unused)) static void ASTabViewImpl_$Lambda$1_initWithASIWidget_(ASTabViewImpl_$Lambda$1 *self, id<ASIWidget> capture$0);

__attribute__((unused)) static ASTabViewImpl_$Lambda$1 *new_ASTabViewImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASTabViewImpl_$Lambda$1 *create_ASTabViewImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0);

NSString *ASTabViewImpl_LOCAL_NAME = @"com.google.android.material.tabs.TabLayout.TabView";
NSString *ASTabViewImpl_GROUP_NAME = @"com.google.android.material.tabs.TabLayout.TabView";

@implementation ASTabViewImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"baselineAligned"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"baselineAlignedChildIndex"])) withTypeWithNSString:@"int"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"divider"])) withTypeWithNSString:@"drawable"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"gravity"])) withTypeWithNSString:@"gravity"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"measureWithLargestChild"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"weightSum"])) withTypeWithNSString:@"float"]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"com.google.android.material.tabs.TabLayout.TabView.divider", new_ASTabViewImpl_Divider_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"showDividers"])) withTypeWithNSString:@"com.google.android.material.tabs.TabLayout.TabView.divider"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"dividerPadding"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_gravity"])) withTypeWithNSString:@"gravity"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_weight"])) withTypeWithNSString:@"float"])) forChild]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASTabViewImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASTabViewImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASTabViewImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASTabViewImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  tabView_ = new_ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(self, (ADMTabLayout *) cast_chk([((id<ASHasWidgets>) nil_chk([((id<ASHasWidgets>) nil_chk([self getParent])) getParent])) asWidget], [ADMTabLayout class]));
  ASTabViewImpl_nativeCreateWithJavaUtilMap_(self, params);
  ASTabViewImpl_createCanvas(self);
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASTabViewImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASTabViewImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return tabView_;
}

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w {
  jboolean remove = [super removeWithASIWidget:w];
  [((ADMTabLayout_TabView *) nil_chk(tabView_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASTabViewImpl_nativeRemoveViewWithASIWidget_(self, w);
  return remove;
}

- (jboolean)removeWithInt:(jint)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  jboolean remove = [super removeWithInt:index];
  if (index + 1 <= [((ADMTabLayout_TabView *) nil_chk(tabView_)) getChildCount]) {
    [((ADMTabLayout_TabView *) nil_chk(tabView_)) removeViewAtWithInt:index];
    ASTabViewImpl_nativeRemoveViewWithASIWidget_(self, widget);
  }
  return remove;
}

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget {
  ASTabViewImpl_nativeRemoveViewWithASIWidget_(self, widget);
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASTabViewImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ADMTabLayout_TabView *) nil_chk(tabView_)) addViewWithADView:view];
    }
    else {
      [((ADMTabLayout_TabView *) nil_chk(tabView_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASTabViewImpl_createLayoutParamsWithADView_(self, view);
}

- (ADLinearLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASTabViewImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADLinearLayout_LayoutParams *layoutParams = ASTabViewImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_weight" }, 4)) {
    case 0:
    ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 2:
    {
      ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->gravity_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 3:
    {
      ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->weight_ = [((JavaLangFloat *) nil_chk(((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class])))) floatValue];
    }
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADLinearLayout_LayoutParams *layoutParams = ASTabViewImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_weight" }, 4)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->height_);
    case 2:
    {
      return JavaLangInteger_valueOfWithInt_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->gravity_);
    }
    case 3:
    {
      return JavaLangFloat_valueOfWithFloat_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->weight_);
    }
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASTabViewImpl_TabViewExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"baselineAligned", @"baselineAlignedChildIndex", @"divider", @"gravity", @"measureWithLargestChild", @"weightSum", @"showDividers", @"dividerPadding" }, 8)) {
    case 0:
    {
      [((ADMTabLayout_TabView *) nil_chk(tabView_)) setBaselineAlignedWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
    }
    break;
    case 1:
    {
      [((ADMTabLayout_TabView *) nil_chk(tabView_)) setBaselineAlignedChildIndexWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 2:
    {
      {
        [((ADMTabLayout_TabView *) nil_chk(tabView_)) setDividerDrawableWithADDrawable:(ADDrawable *) cast_chk(objValue, [ADDrawable class])];
      }
    }
    break;
    case 3:
    {
      [((ADMTabLayout_TabView *) nil_chk(tabView_)) setGravityWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 4:
    {
      {
        [((ADMTabLayout_TabView *) nil_chk(tabView_)) setMeasureWithLargestChildEnabledWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
      }
    }
    break;
    case 5:
    {
      [((ADMTabLayout_TabView *) nil_chk(tabView_)) setWeightSumWithFloat:[((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue]];
    }
    break;
    case 6:
    {
      ASTabViewImpl_setShowDividersWithId_(self, objValue);
    }
    break;
    case 7:
    {
      ASTabViewImpl_setDividerPaddingWithId_(self, objValue);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"baselineAligned", @"baselineAlignedChildIndex", @"divider", @"gravity", @"measureWithLargestChild", @"weightSum", @"showDividers", @"dividerPadding" }, 8)) {
    case 0:
    {
      return JavaLangBoolean_valueOfWithBoolean_([((ADMTabLayout_TabView *) nil_chk(tabView_)) isBaselineAligned]);
    }
    case 1:
    {
      return JavaLangInteger_valueOfWithInt_([((ADMTabLayout_TabView *) nil_chk(tabView_)) getBaselineAlignedChildIndex]);
    }
    case 2:
    {
      {
        return [((ADMTabLayout_TabView *) nil_chk(tabView_)) getDividerDrawable];
      }
    }
    case 3:
    {
      {
        return JavaLangInteger_valueOfWithInt_([((ADMTabLayout_TabView *) nil_chk(tabView_)) getGravity]);
      }
    }
    case 4:
    {
      {
        return JavaLangBoolean_valueOfWithBoolean_([((ADMTabLayout_TabView *) nil_chk(tabView_)) isMeasureWithLargestChildEnabled]);
      }
    }
    case 5:
    {
      return JavaLangFloat_valueOfWithFloat_([((ADMTabLayout_TabView *) nil_chk(tabView_)) getWeightSum]);
    }
    case 6:
    {
      return ASTabViewImpl_getShowDividers(self);
    }
    case 7:
    {
      return ASTabViewImpl_getDividerPadding(self);
    }
  }
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setDividerPaddingWithId:(id)objValue {
  ASTabViewImpl_setDividerPaddingWithId_(self, objValue);
}

- (void)setShowDividersWithId:(id)objValue {
  ASTabViewImpl_setShowDividersWithId_(self, objValue);
}

- (id)getDividerPadding {
  return ASTabViewImpl_getDividerPadding(self);
}

- (id)getShowDividers {
  return ASTabViewImpl_getShowDividers(self);
}

- (void)createCanvas {
  ASTabViewImpl_createCanvas(self);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADMTabLayout_TabView *) nil_chk(tabView_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(jboolean)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (id)getPluginWithNSString:(NSString *)plugin {
  return [((id<ASIAttributable>) nil_chk(ASWidgetFactory_getAttributableWithNSString_(plugin))) newInstanceWithASIWidget:self];
}

- (ASTabViewImpl_TabViewBean *)getBean {
  if (bean_ == nil) {
    bean_ = new_ASTabViewImpl_TabViewBean_initWithASTabViewImpl_(self);
  }
  return bean_;
}

- (ASTabViewImpl_TabViewCommandBuilder *)getBuilder {
  if (builder_ == nil) {
    builder_ = new_ASTabViewImpl_TabViewCommandBuilder_initWithASTabViewImpl_(self);
  }
  return builder_;
}

- (ASTabViewImpl_TabViewParamsBean *)getParamsBean {
  if (paramsBean_ == nil) {
    paramsBean_ = new_ASTabViewImpl_TabViewParamsBean_initWithASTabViewImpl_(self);
  }
  return paramsBean_;
}

- (ASTabViewImpl_TabViewCommandParamsBuilder *)getParamsBuilder {
  if (paramsBuilder_ == nil) {
    paramsBuilder_ = new_ASTabViewImpl_TabViewCommandParamsBuilder_initWithASTabViewImpl_(self);
  }
  return paramsBuilder_;
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASTabViewImpl_nativeCreateWithJavaUtilMap_(self, params);
}

- (void)createView {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 9, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 13, -1, -1, -1, -1 },
    { NULL, "LADLinearLayout_LayoutParams;", 0x2, 14, 13, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 20, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 21, 22, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 24, 25, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 26, 25, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 27, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 29, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 30, 1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewParamsBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 31, 32, -1, 33, -1, -1 },
    { NULL, "V", 0x101, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(nativeRemoveViewWithASIWidget:);
  methods[11].selector = @selector(addWithASIWidget:withInt:);
  methods[12].selector = @selector(createLayoutParamsWithADView:);
  methods[13].selector = @selector(getLayoutParamsWithADView:);
  methods[14].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[15].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[16].selector = @selector(getViewClass);
  methods[17].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[18].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[19].selector = @selector(asNativeWidget);
  methods[20].selector = @selector(checkIosVersionWithNSString:);
  methods[21].selector = @selector(requestLayout);
  methods[22].selector = @selector(invalidate);
  methods[23].selector = @selector(setDividerPaddingWithId:);
  methods[24].selector = @selector(setShowDividersWithId:);
  methods[25].selector = @selector(getDividerPadding);
  methods[26].selector = @selector(getShowDividers);
  methods[27].selector = @selector(createCanvas);
  methods[28].selector = @selector(setIdWithNSString:);
  methods[29].selector = @selector(setVisibleWithBoolean:);
  methods[30].selector = @selector(getPluginWithNSString:);
  methods[31].selector = @selector(getBean);
  methods[32].selector = @selector(getBuilder);
  methods[33].selector = @selector(getParamsBean);
  methods[34].selector = @selector(getParamsBuilder);
  methods[35].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[36].selector = @selector(createView);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "canvas_", "LADCanvas;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 34, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 35, -1, -1 },
    { "tabView_", "LADMTabLayout_TabView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "builder_", "LASTabViewImpl_TabViewCommandBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "bean_", "LASTabViewImpl_TabViewBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBuilder_", "LASTabViewImpl_TabViewCommandParamsBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBean_", "LASTabViewImpl_TabViewParamsBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "nativeRemoveView", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "setDividerPadding", "LNSObject;", "setShowDividers", "setId", "setVisible", "Z", "getPlugin", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", &ASTabViewImpl_LOCAL_NAME, &ASTabViewImpl_GROUP_NAME, "LASTabViewImpl_Divider;LASTabViewImpl_TabViewExt;LASTabViewImpl_CanvasImpl;LASTabViewImpl_TabViewCommandBuilder;LASTabViewImpl_TabViewBean;LASTabViewImpl_TabViewParamsBean;LASTabViewImpl_TabViewCommandParamsBuilder;" };
  static const J2ObjcClassInfo _ASTabViewImpl = { "TabViewImpl", "com.ashera.tablayout", ptrTable, methods, fields, 7, 0x1, 37, 9, -1, 36, -1, -1, -1 };
  return &_ASTabViewImpl;
}

@end

void ASTabViewImpl_init(ASTabViewImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASTabViewImpl_GROUP_NAME, ASTabViewImpl_LOCAL_NAME);
}

ASTabViewImpl *new_ASTabViewImpl_init() {
  J2OBJC_NEW_IMPL(ASTabViewImpl, init)
}

ASTabViewImpl *create_ASTabViewImpl_init() {
  J2OBJC_CREATE_IMPL(ASTabViewImpl, init)
}

void ASTabViewImpl_initWithNSString_(ASTabViewImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASTabViewImpl_GROUP_NAME, localname);
}

ASTabViewImpl *new_ASTabViewImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASTabViewImpl, initWithNSString_, localname)
}

ASTabViewImpl *create_ASTabViewImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl, initWithNSString_, localname)
}

void ASTabViewImpl_initWithNSString_withNSString_(ASTabViewImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ASTabViewImpl *new_ASTabViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASTabViewImpl, initWithNSString_withNSString_, groupName, localname)
}

ASTabViewImpl *create_ASTabViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASTabViewImpl_setWidgetOnNativeClass(ASTabViewImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASTabViewImpl_nativeRemoveViewWithASIWidget_(ASTabViewImpl *self, id<ASIWidget> widget) {
  ADLayoutTransition *layoutTransition = [((ADMTabLayout_TabView *) nil_chk(self->tabView_)) getLayoutTransition];
  if (layoutTransition != nil && ([layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_CHANGE_DISAPPEARING] || [layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_DISAPPEARING])) {
    [self addToBufferedRunnablesWithJavaLangRunnable:new_ASTabViewImpl_$Lambda$1_initWithASIWidget_(widget)];
  }
  else {
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
}

void ASTabViewImpl_createLayoutParamsWithADView_(ASTabViewImpl *self, ADView *view) {
  ADLinearLayout_LayoutParams *layoutParams = (ADLinearLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADLinearLayout_LayoutParams class]);
  layoutParams = (ADLinearLayout_LayoutParams *) cast_chk([view getLayoutParams], [ADLinearLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ADLinearLayout_LayoutParams_initWithInt_withInt_(-2, -2);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ADLinearLayout_LayoutParams *ASTabViewImpl_getLayoutParamsWithADView_(ASTabViewImpl *self, ADView *view) {
  return (ADLinearLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADLinearLayout_LayoutParams class]);
}

void ASTabViewImpl_setDividerPaddingWithId_(ASTabViewImpl *self, id objValue) {
  {
    [((ADMTabLayout_TabView *) nil_chk(self->tabView_)) setDividerPaddingWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
  }
}

void ASTabViewImpl_setShowDividersWithId_(ASTabViewImpl *self, id objValue) {
  {
    [((ADMTabLayout_TabView *) nil_chk(self->tabView_)) setShowDividersWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
  }
}

id ASTabViewImpl_getDividerPadding(ASTabViewImpl *self) {
  {
    return JavaLangInteger_valueOfWithInt_([((ADMTabLayout_TabView *) nil_chk(self->tabView_)) getDividerPadding]);
  }
}

id ASTabViewImpl_getShowDividers(ASTabViewImpl *self) {
  {
    return JavaLangInteger_valueOfWithInt_([((ADMTabLayout_TabView *) nil_chk(self->tabView_)) getShowDividers]);
  }
}

void ASTabViewImpl_createCanvas(ASTabViewImpl *self) {
  self->canvas_ = new_ASTabViewImpl_CanvasImpl_initWithASIWidget_(self);
}

void ASTabViewImpl_nativeCreateWithJavaUtilMap_(ASTabViewImpl *self, id<JavaUtilMap> params) {
  [self createView];
  [((ADMTabLayout_TabView *) nil_chk(self->tabView_)) initTabView];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl)

@implementation ASTabViewImpl_Divider

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASTabViewImpl_Divider_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASTabViewImpl;" };
  static const J2ObjcClassInfo _ASTabViewImpl_Divider = { "Divider", "com.ashera.tablayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASTabViewImpl_Divider;
}

@end

void ASTabViewImpl_Divider_init(ASTabViewImpl_Divider *self) {
  ASAbstractBitFlagConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"none" withId:JavaLangInteger_valueOfWithInt_((jint) 0x0)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"beginning" withId:JavaLangInteger_valueOfWithInt_((jint) 0x1)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"end" withId:JavaLangInteger_valueOfWithInt_((jint) 0x4)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"middle" withId:JavaLangInteger_valueOfWithInt_((jint) 0x2)];
  }
}

ASTabViewImpl_Divider *new_ASTabViewImpl_Divider_init() {
  J2OBJC_NEW_IMPL(ASTabViewImpl_Divider, init)
}

ASTabViewImpl_Divider *create_ASTabViewImpl_Divider_init() {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_Divider, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl_Divider)

@implementation ASTabViewImpl_TabViewExt

- (id<ASIWidget>)getWidget {
  return this$1_;
}

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASTabViewImpl:(ASTabViewImpl *)outer$
                     withADMTabLayout:(ADMTabLayout *)tablayout {
  ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(self, outer$, tablayout);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$1_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$1_, l, t, r, b);
  if (![self isOverlay]) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$1_ asNativeWidget], l, t, r, b);
  }
  [this$1_ replayBufferedEvents];
  [((id<ADCanvas>) nil_chk(this$1_->canvas_)) reset];
  [self onDrawWithADCanvas:this$1_->canvas_];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$1_);
  overlays_ = ASViewImpl_drawOverlayWithASIWidget_withJavaUtilList_(this$1_, overlays_);
  id<ASIWidgetLifeCycleListener> listener = [this$1_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$1_ isInvalidateOnFrameChange] && [this$1_ isInitialised]) {
    [this$1_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  if (![this$1_ isWidgetDisposed]) {
    ASViewImpl_drawableStateChangedWithASIWidget_(this$1_);
  }
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$1_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:this$1_];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$1_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$1_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$1_ getParent])) removeWithASIWidget:this$1_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$1_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$1_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$1_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$1_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$1_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$1_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$1_ setAttributeWithNSString:name withId:value withBoolean:!([value isKindOfClass:[NSString class]])];
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$1_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$1_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$1_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$1_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$1_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$1_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$1_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$1_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$1_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$1_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$1_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$1_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$1_);
}

- (void)endViewTransitionWithADView:(ADView *)view {
  [super endViewTransitionWithADView:view];
  [this$1_ runBufferedRunnables];
}

- (void)__javaClone:(ASTabViewImpl_TabViewExt *)original {
  [super __javaClone:original];
  JreRelease(this$1_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 35, 36, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASTabViewImpl:withADMTabLayout:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(setState0WithId:);
  methods[26].selector = @selector(setState1WithId:);
  methods[27].selector = @selector(setState2WithId:);
  methods[28].selector = @selector(setState3WithId:);
  methods[29].selector = @selector(setState4WithId:);
  methods[30].selector = @selector(state0);
  methods[31].selector = @selector(state1);
  methods[32].selector = @selector(state2);
  methods[33].selector = @selector(state3);
  methods[34].selector = @selector(state4);
  methods[35].selector = @selector(stateYes);
  methods[36].selector = @selector(stateNo);
  methods[37].selector = @selector(endViewTransitionWithADView:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$1_", "LASTabViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "overlays_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 37, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 38, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASTabViewImpl;LADMTabLayout;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "endViewTransition", "LADView;", "Ljava/util/List<Lcom/ashera/widget/IWidget;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;", "LASTabViewImpl;" };
  static const J2ObjcClassInfo _ASTabViewImpl_TabViewExt = { "TabViewExt", "com.ashera.tablayout", ptrTable, methods, fields, 7, 0x1, 38, 7, 39, -1, -1, -1, -1 };
  return &_ASTabViewImpl_TabViewExt;
}

@end

void ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(ASTabViewImpl_TabViewExt *self, ASTabViewImpl *outer$, ADMTabLayout *tablayout) {
  self->this$1_ = outer$;
  ADMTabLayout_TabView_initWithADMTabLayout_withADContext_(self, nil_chk(tablayout), [tablayout getContext]);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASTabViewImpl_TabViewExt *new_ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(ASTabViewImpl *outer$, ADMTabLayout *tablayout) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_TabViewExt, initWithASTabViewImpl_withADMTabLayout_, outer$, tablayout)
}

ASTabViewImpl_TabViewExt *create_ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(ASTabViewImpl *outer$, ADMTabLayout *tablayout) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_TabViewExt, initWithASTabViewImpl_withADMTabLayout_, outer$, tablayout)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl_TabViewExt)

@implementation ASTabViewImpl_CanvasImpl

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget {
  ASTabViewImpl_CanvasImpl_initWithASIWidget_(self, widget);
  return self;
}

- (void)drawWithADDrawable:(ADDrawable *)mDivider {
  for (id __strong divider in nil_chk(imageViews_)) {
    if (ASViewImpl_getXWithId_(divider) == [((ADDrawable *) nil_chk(mDivider)) getLeft] && ASViewImpl_getYWithId_(divider) == [mDivider getTop]) {
      return;
    }
  }
  id image = [((ADDrawable *) nil_chk(mDivider)) getDrawable];
  if (image != nil) {
    if ([image isKindOfClass:[JavaLangInteger class]]) {
      image = ASViewImpl_getColorWithId_(image);
    }
    id imageView = [self nativeCreateImageViewWithId:image];
    if (requiresAttrChangeListener_) {
      [mDivider setAttributeChangeListenerWithADDrawable_AttributeChangeListener:new_ASTabViewImpl_CanvasImpl_$Lambda$1_initWithId_(imageView)];
    }
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_(imageView, [mDivider getLeft], [mDivider getTop], [mDivider getRight], [mDivider getBottom]);
    [((id<JavaUtilList>) nil_chk(imageViews_)) addWithId:imageView];
    ASViewGroupImpl_nativeAddViewWithId_withId_([((id<ASIWidget>) nil_chk(widget_)) asNativeWidget], imageView);
  }
}

- (void)reset {
  if (canvasReset_) {
    for (id __strong imageView in nil_chk(imageViews_)) {
      ASViewGroupImpl_removeViewWithId_(imageView);
    }
    [imageViews_ clear];
  }
}

- (id)nativeCreateImageViewWithId:(id)image {
  ASUIImageView* imageView = [ASUIImageView new];
  if ([image isKindOfClass:[UIImage class]]) {
    imageView.image = image;
    imageView.backgroundColor = nil;
  }else if ([image isKindOfClass:[UIColor class]]) {
    imageView.backgroundColor = image;
    imageView.image = nil;
  }
  return imageView;
}

- (void)translateWithInt:(jint)arg0
                 withInt:(jint)arg1 {
  ADCanvas_translateWithInt_withInt_(self, arg0, arg1);
}

- (void)__javaClone:(ASTabViewImpl_CanvasImpl *)original {
  [super __javaClone:original];
  JreRelease(widget_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x101, 3, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASIWidget:);
  methods[1].selector = @selector(drawWithADDrawable:);
  methods[2].selector = @selector(reset);
  methods[3].selector = @selector(nativeCreateImageViewWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "canvasReset_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "requiresAttrChangeListener_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "imageViews_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 5, -1 },
    { "widget_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASIWidget;", "draw", "LADDrawable;", "nativeCreateImageView", "LNSObject;", "Ljava/util/List<Ljava/lang/Object;>;", "LASTabViewImpl;" };
  static const J2ObjcClassInfo _ASTabViewImpl_CanvasImpl = { "CanvasImpl", "com.ashera.tablayout", ptrTable, methods, fields, 7, 0x1a, 4, 4, 6, -1, -1, -1, -1 };
  return &_ASTabViewImpl_CanvasImpl;
}

@end

void ASTabViewImpl_CanvasImpl_initWithASIWidget_(ASTabViewImpl_CanvasImpl *self, id<ASIWidget> widget) {
  NSObject_init(self);
  self->canvasReset_ = true;
  self->requiresAttrChangeListener_ = false;
  self->imageViews_ = new_JavaUtilArrayList_init();
  self->widget_ = widget;
}

ASTabViewImpl_CanvasImpl *new_ASTabViewImpl_CanvasImpl_initWithASIWidget_(id<ASIWidget> widget) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_CanvasImpl, initWithASIWidget_, widget)
}

ASTabViewImpl_CanvasImpl *create_ASTabViewImpl_CanvasImpl_initWithASIWidget_(id<ASIWidget> widget) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_CanvasImpl, initWithASIWidget_, widget)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl_CanvasImpl)

@implementation ASTabViewImpl_CanvasImpl_$Lambda$1

- (void)onAttributeChangeWithNSString:(NSString *)name
                               withId:(id)value {
  {
    ADRect *rect;
    jint alpha;
    switch (JreIndexOfStr(name, (id[]){ @"bounds", @"alpha" }, 2)) {
      case 0:
      rect = (ADRect *) cast_chk(value, [ADRect class]);
      ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_(val$imageView_, ((ADRect *) nil_chk(rect))->left_, rect->top_, rect->right_, rect->bottom_);
      break;
      case 1:
      alpha = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(value, [JavaLangInteger class]))) intValue];
      ASViewImpl_setAlphaWithId_withId_(val$imageView_, JavaLangFloat_valueOfWithFloat_(alpha / 255.0f));
      break;
      default:
      break;
    }
  }
}

@end

void ASTabViewImpl_CanvasImpl_$Lambda$1_initWithId_(ASTabViewImpl_CanvasImpl_$Lambda$1 *self, id capture$0) {
  self->val$imageView_ = capture$0;
  NSObject_init(self);
}

ASTabViewImpl_CanvasImpl_$Lambda$1 *new_ASTabViewImpl_CanvasImpl_$Lambda$1_initWithId_(id capture$0) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_CanvasImpl_$Lambda$1, initWithId_, capture$0)
}

ASTabViewImpl_CanvasImpl_$Lambda$1 *create_ASTabViewImpl_CanvasImpl_$Lambda$1_initWithId_(id capture$0) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_CanvasImpl_$Lambda$1, initWithId_, capture$0)
}

@implementation ASTabViewImpl_TabViewCommandBuilder

- (instancetype)initWithASTabViewImpl:(ASTabViewImpl *)outer$ {
  ASTabViewImpl_TabViewCommandBuilder_initWithASTabViewImpl_(self, outer$);
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)executeWithBoolean:(jboolean)setter {
  if (setter) {
    [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
  [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetBaselineAligned {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"baselineAligned"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)isBaselineAligned {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"baselineAligned"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setBaselineAlignedWithBoolean:(jboolean)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"baselineAligned"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangBoolean_valueOfWithBoolean_(value)];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetBaselineAlignedChildIndex {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"baselineAlignedChildIndex"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getBaselineAlignedChildIndex {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"baselineAlignedChildIndex"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setBaselineAlignedChildIndexWithInt:(jint)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"baselineAlignedChildIndex"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangInteger_valueOfWithInt_(value)];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetDivider {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"divider"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getDivider {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"divider"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setDividerWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"divider"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"gravity"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setGravityWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetMeasureWithLargestChild {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"measureWithLargestChild"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)isMeasureWithLargestChild {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"measureWithLargestChild"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setMeasureWithLargestChildWithBoolean:(jboolean)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"measureWithLargestChild"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangBoolean_valueOfWithBoolean_(value)];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetWeightSum {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"weightSum"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getWeightSum {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"weightSum"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setWeightSumWithFloat:(jfloat)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"weightSum"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangFloat_valueOfWithFloat_(value)];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetShowDividers {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"showDividers"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getShowDividers {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"showDividers"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setShowDividersWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"showDividers"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASTabViewImpl_TabViewCommandBuilder *)tryGetDividerPadding {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"dividerPadding"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getDividerPadding {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"dividerPadding"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandBuilder *)setDividerPaddingWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"dividerPadding"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 3, 2, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 8, 7, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 9, 2, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 12, 7, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandBuilder;", 0x1, 13, 7, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASTabViewImpl:);
  methods[1].selector = @selector(executeWithBoolean:);
  methods[2].selector = @selector(tryGetBaselineAligned);
  methods[3].selector = @selector(isBaselineAligned);
  methods[4].selector = @selector(setBaselineAlignedWithBoolean:);
  methods[5].selector = @selector(tryGetBaselineAlignedChildIndex);
  methods[6].selector = @selector(getBaselineAlignedChildIndex);
  methods[7].selector = @selector(setBaselineAlignedChildIndexWithInt:);
  methods[8].selector = @selector(tryGetDivider);
  methods[9].selector = @selector(getDivider);
  methods[10].selector = @selector(setDividerWithNSString:);
  methods[11].selector = @selector(tryGetGravity);
  methods[12].selector = @selector(getGravity);
  methods[13].selector = @selector(setGravityWithNSString:);
  methods[14].selector = @selector(tryGetMeasureWithLargestChild);
  methods[15].selector = @selector(isMeasureWithLargestChild);
  methods[16].selector = @selector(setMeasureWithLargestChildWithBoolean:);
  methods[17].selector = @selector(tryGetWeightSum);
  methods[18].selector = @selector(getWeightSum);
  methods[19].selector = @selector(setWeightSumWithFloat:);
  methods[20].selector = @selector(tryGetShowDividers);
  methods[21].selector = @selector(getShowDividers);
  methods[22].selector = @selector(setShowDividersWithNSString:);
  methods[23].selector = @selector(tryGetDividerPadding);
  methods[24].selector = @selector(getDividerPadding);
  methods[25].selector = @selector(setDividerPaddingWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASTabViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASTabViewImpl;", "execute", "Z", "setBaselineAligned", "setBaselineAlignedChildIndex", "I", "setDivider", "LNSString;", "setGravity", "setMeasureWithLargestChild", "setWeightSum", "F", "setShowDividers", "setDividerPadding", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandBuilder<Lcom/ashera/tablayout/TabViewImpl$TabViewCommandBuilder;>;" };
  static const J2ObjcClassInfo _ASTabViewImpl_TabViewCommandBuilder = { "TabViewCommandBuilder", "com.ashera.tablayout", ptrTable, methods, fields, 7, 0x1, 26, 1, 0, -1, -1, 14, -1 };
  return &_ASTabViewImpl_TabViewCommandBuilder;
}

@end

void ASTabViewImpl_TabViewCommandBuilder_initWithASTabViewImpl_(ASTabViewImpl_TabViewCommandBuilder *self, ASTabViewImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupCommandBuilder_init(self);
}

ASTabViewImpl_TabViewCommandBuilder *new_ASTabViewImpl_TabViewCommandBuilder_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_TabViewCommandBuilder, initWithASTabViewImpl_, outer$)
}

ASTabViewImpl_TabViewCommandBuilder *create_ASTabViewImpl_TabViewCommandBuilder_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_TabViewCommandBuilder, initWithASTabViewImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl_TabViewCommandBuilder)

@implementation ASTabViewImpl_TabViewBean

- (instancetype)initWithASTabViewImpl:(ASTabViewImpl *)outer$ {
  ASTabViewImpl_TabViewBean_initWithASTabViewImpl_(self, outer$);
  return self;
}

- (id)isBaselineAligned {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetBaselineAligned])) executeWithBoolean:false])) isBaselineAligned];
}

- (void)setBaselineAlignedWithBoolean:(jboolean)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setBaselineAlignedWithBoolean:value])) executeWithBoolean:true];
}

- (id)getBaselineAlignedChildIndex {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetBaselineAlignedChildIndex])) executeWithBoolean:false])) getBaselineAlignedChildIndex];
}

- (void)setBaselineAlignedChildIndexWithInt:(jint)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setBaselineAlignedChildIndexWithInt:value])) executeWithBoolean:true];
}

- (id)getDivider {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetDivider])) executeWithBoolean:false])) getDivider];
}

- (void)setDividerWithNSString:(NSString *)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setDividerWithNSString:value])) executeWithBoolean:true];
}

- (id)getGravity {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetGravity])) executeWithBoolean:false])) getGravity];
}

- (void)setGravityWithNSString:(NSString *)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setGravityWithNSString:value])) executeWithBoolean:true];
}

- (id)isMeasureWithLargestChild {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetMeasureWithLargestChild])) executeWithBoolean:false])) isMeasureWithLargestChild];
}

- (void)setMeasureWithLargestChildWithBoolean:(jboolean)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setMeasureWithLargestChildWithBoolean:value])) executeWithBoolean:true];
}

- (id)getWeightSum {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetWeightSum])) executeWithBoolean:false])) getWeightSum];
}

- (void)setWeightSumWithFloat:(jfloat)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setWeightSumWithFloat:value])) executeWithBoolean:true];
}

- (id)getShowDividers {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetShowDividers])) executeWithBoolean:false])) getShowDividers];
}

- (void)setShowDividersWithNSString:(NSString *)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setShowDividersWithNSString:value])) executeWithBoolean:true];
}

- (id)getDividerPadding {
  return [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) tryGetDividerPadding])) executeWithBoolean:false])) getDividerPadding];
}

- (void)setDividerPaddingWithNSString:(NSString *)value {
  (void) [((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setDividerPaddingWithNSString:value])) executeWithBoolean:true];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 7, 6, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 8, 2, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 11, 6, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 12, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASTabViewImpl:);
  methods[1].selector = @selector(isBaselineAligned);
  methods[2].selector = @selector(setBaselineAlignedWithBoolean:);
  methods[3].selector = @selector(getBaselineAlignedChildIndex);
  methods[4].selector = @selector(setBaselineAlignedChildIndexWithInt:);
  methods[5].selector = @selector(getDivider);
  methods[6].selector = @selector(setDividerWithNSString:);
  methods[7].selector = @selector(getGravity);
  methods[8].selector = @selector(setGravityWithNSString:);
  methods[9].selector = @selector(isMeasureWithLargestChild);
  methods[10].selector = @selector(setMeasureWithLargestChildWithBoolean:);
  methods[11].selector = @selector(getWeightSum);
  methods[12].selector = @selector(setWeightSumWithFloat:);
  methods[13].selector = @selector(getShowDividers);
  methods[14].selector = @selector(setShowDividersWithNSString:);
  methods[15].selector = @selector(getDividerPadding);
  methods[16].selector = @selector(setDividerPaddingWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASTabViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASTabViewImpl;", "setBaselineAligned", "Z", "setBaselineAlignedChildIndex", "I", "setDivider", "LNSString;", "setGravity", "setMeasureWithLargestChild", "setWeightSum", "F", "setShowDividers", "setDividerPadding" };
  static const J2ObjcClassInfo _ASTabViewImpl_TabViewBean = { "TabViewBean", "com.ashera.tablayout", ptrTable, methods, fields, 7, 0x1, 17, 1, 0, -1, -1, -1, -1 };
  return &_ASTabViewImpl_TabViewBean;
}

@end

void ASTabViewImpl_TabViewBean_initWithASTabViewImpl_(ASTabViewImpl_TabViewBean *self, ASTabViewImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupBean_initWithASIWidget_(self, outer$);
}

ASTabViewImpl_TabViewBean *new_ASTabViewImpl_TabViewBean_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_TabViewBean, initWithASTabViewImpl_, outer$)
}

ASTabViewImpl_TabViewBean *create_ASTabViewImpl_TabViewBean_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_TabViewBean, initWithASTabViewImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl_TabViewBean)

@implementation ASTabViewImpl_TabViewParamsBean

- (instancetype)initWithASTabViewImpl:(ASTabViewImpl *)outer$ {
  ASTabViewImpl_TabViewParamsBean_initWithASTabViewImpl_(self, outer$);
  return self;
}

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutGravity])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutGravity];
}

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutGravityWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutWeightWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutWeight])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutWeight];
}

- (void)setLayoutWeightWithASIWidget:(id<ASIWidget>)w
                           withFloat:(jfloat)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([((ASTabViewImpl_TabViewCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutWeightWithFloat:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 5, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASTabViewImpl:);
  methods[1].selector = @selector(getLayoutGravityWithASIWidget:);
  methods[2].selector = @selector(setLayoutGravityWithASIWidget:withNSString:);
  methods[3].selector = @selector(getLayoutWeightWithASIWidget:);
  methods[4].selector = @selector(setLayoutWeightWithASIWidget:withFloat:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASTabViewImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASTabViewImpl;", "getLayoutGravity", "LASIWidget;", "setLayoutGravity", "LASIWidget;LNSString;", "getLayoutWeight", "setLayoutWeight", "LASIWidget;F" };
  static const J2ObjcClassInfo _ASTabViewImpl_TabViewParamsBean = { "TabViewParamsBean", "com.ashera.tablayout", ptrTable, methods, fields, 7, 0x1, 5, 1, 0, -1, -1, -1, -1 };
  return &_ASTabViewImpl_TabViewParamsBean;
}

@end

void ASTabViewImpl_TabViewParamsBean_initWithASTabViewImpl_(ASTabViewImpl_TabViewParamsBean *self, ASTabViewImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupParamsBean_init(self);
}

ASTabViewImpl_TabViewParamsBean *new_ASTabViewImpl_TabViewParamsBean_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_TabViewParamsBean, initWithASTabViewImpl_, outer$)
}

ASTabViewImpl_TabViewParamsBean *create_ASTabViewImpl_TabViewParamsBean_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_TabViewParamsBean, initWithASTabViewImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl_TabViewParamsBean)

@implementation ASTabViewImpl_TabViewCommandParamsBuilder

- (instancetype)initWithASTabViewImpl:(ASTabViewImpl *)outer$ {
  ASTabViewImpl_TabViewCommandParamsBuilder_initWithASTabViewImpl_(self, outer$);
  return self;
}

- (ASTabViewImpl_TabViewCommandParamsBuilder *)tryGetLayoutGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASTabViewImpl_TabViewCommandParamsBuilder *)tryGetLayoutWeight {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_weight"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutWeight {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_weight"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASTabViewImpl_TabViewCommandParamsBuilder *)setLayoutWeightWithFloat:(jfloat)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_weight"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangFloat_valueOfWithFloat_(value)];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandParamsBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASTabViewImpl_TabViewCommandParamsBuilder;", 0x1, 3, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASTabViewImpl:);
  methods[1].selector = @selector(tryGetLayoutGravity);
  methods[2].selector = @selector(getLayoutGravity);
  methods[3].selector = @selector(setLayoutGravityWithNSString:);
  methods[4].selector = @selector(tryGetLayoutWeight);
  methods[5].selector = @selector(getLayoutWeight);
  methods[6].selector = @selector(setLayoutWeightWithFloat:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASTabViewImpl;", "setLayoutGravity", "LNSString;", "setLayoutWeight", "F", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandParamsBuilder<Lcom/ashera/tablayout/TabViewImpl$TabViewCommandParamsBuilder;>;" };
  static const J2ObjcClassInfo _ASTabViewImpl_TabViewCommandParamsBuilder = { "TabViewCommandParamsBuilder", "com.ashera.tablayout", ptrTable, methods, NULL, 7, 0x1, 7, 0, 0, -1, -1, 5, -1 };
  return &_ASTabViewImpl_TabViewCommandParamsBuilder;
}

@end

void ASTabViewImpl_TabViewCommandParamsBuilder_initWithASTabViewImpl_(ASTabViewImpl_TabViewCommandParamsBuilder *self, ASTabViewImpl *outer$) {
  ASViewGroupImpl_ViewGroupCommandParamsBuilder_init(self);
}

ASTabViewImpl_TabViewCommandParamsBuilder *new_ASTabViewImpl_TabViewCommandParamsBuilder_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_TabViewCommandParamsBuilder, initWithASTabViewImpl_, outer$)
}

ASTabViewImpl_TabViewCommandParamsBuilder *create_ASTabViewImpl_TabViewCommandParamsBuilder_initWithASTabViewImpl_(ASTabViewImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_TabViewCommandParamsBuilder, initWithASTabViewImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTabViewImpl_TabViewCommandParamsBuilder)

@implementation ASTabViewImpl_$Lambda$1

- (void)run {
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(val$widget_);
}

@end

void ASTabViewImpl_$Lambda$1_initWithASIWidget_(ASTabViewImpl_$Lambda$1 *self, id<ASIWidget> capture$0) {
  self->val$widget_ = capture$0;
  NSObject_init(self);
}

ASTabViewImpl_$Lambda$1 *new_ASTabViewImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_NEW_IMPL(ASTabViewImpl_$Lambda$1, initWithASIWidget_, capture$0)
}

ASTabViewImpl_$Lambda$1 *create_ASTabViewImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_CREATE_IMPL(ASTabViewImpl_$Lambda$1, initWithASIWidget_, capture$0)
}
