//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTabLayoutPlugin\src\main\java\com\ashera\tablayout\TabViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TabViewImpl")
#ifdef RESTRICT_TabViewImpl
#define INCLUDE_ALL_TabViewImpl 0
#else
#define INCLUDE_ALL_TabViewImpl 1
#endif
#undef RESTRICT_TabViewImpl

#if !defined (ASTabViewImpl_) && (INCLUDE_ALL_TabViewImpl || defined(INCLUDE_ASTabViewImpl))
#define ASTabViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASTabViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)createView;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabViewImpl)

inline NSString *ASTabViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASTabViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTabViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTabViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASTabViewImpl_init(ASTabViewImpl *self);

FOUNDATION_EXPORT ASTabViewImpl *new_ASTabViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabViewImpl *create_ASTabViewImpl_init(void);

FOUNDATION_EXPORT void ASTabViewImpl_initWithNSString_(ASTabViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASTabViewImpl *new_ASTabViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabViewImpl *create_ASTabViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASTabViewImpl_initWithNSString_withNSString_(ASTabViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASTabViewImpl *new_ASTabViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabViewImpl *create_ASTabViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASTabViewImpl)

@compatibility_alias ComAsheraTablayoutTabViewImpl ASTabViewImpl;

#endif

#if !defined (ASTabViewImpl_Divider_) && (INCLUDE_ALL_TabViewImpl || defined(INCLUDE_ASTabViewImpl_Divider))
#define ASTabViewImpl_Divider_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTabViewImpl_Divider : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabViewImpl_Divider)

FOUNDATION_EXPORT void ASTabViewImpl_Divider_init(ASTabViewImpl_Divider *self);

FOUNDATION_EXPORT ASTabViewImpl_Divider *new_ASTabViewImpl_Divider_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabViewImpl_Divider *create_ASTabViewImpl_Divider_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTabViewImpl_Divider)

#endif

#if !defined (ASTabViewImpl_TabViewExt_) && (INCLUDE_ALL_TabViewImpl || defined(INCLUDE_ASTabViewImpl_TabViewExt))
#define ASTabViewImpl_TabViewExt_

#define RESTRICT_TabLayout 1
#define INCLUDE_ADMTabLayout_TabView 1
#include "TabLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADMTabLayout;
@class ADRect;
@class ADView;
@class ASTabViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASTabViewImpl_TabViewExt : ADMTabLayout_TabView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASTabViewImpl:(ASTabViewImpl *)outer$
                     withADMTabLayout:(ADMTabLayout *)tablayout;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithADMTabLayout:(ADMTabLayout *)outer$
                       withADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTabViewImpl_TabViewExt)

FOUNDATION_EXPORT void ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(ASTabViewImpl_TabViewExt *self, ASTabViewImpl *outer$, ADMTabLayout *tablayout);

FOUNDATION_EXPORT ASTabViewImpl_TabViewExt *new_ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(ASTabViewImpl *outer$, ADMTabLayout *tablayout) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTabViewImpl_TabViewExt *create_ASTabViewImpl_TabViewExt_initWithASTabViewImpl_withADMTabLayout_(ASTabViewImpl *outer$, ADMTabLayout *tablayout);

J2OBJC_TYPE_LITERAL_HEADER(ASTabViewImpl_TabViewExt)

#endif

#pragma pop_macro("INCLUDE_ALL_TabViewImpl")
